services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MONGODB_URI=${MONGODB_URI}
      - CORS_URL=${CORS_URL}
      - JWT_SECRET=${JWT_SECRET}
    restart: unless-stopped
